CREATE DATABASE IF NOT EXISTS demo;
USE demo;

CREATE TABLE IF NOT EXISTS t (
  k1 INT,
  v1 STRING
)
DUPLICATE KEY(k1)
DISTRIBUTED BY HASH(k1) BUCKETS 1
PROPERTIES("replication_num"="1");

INSERT INTO t VALUES (1,'a'),(2,'b');

SHOW DATABASES;
SHOW TABLES;
SHOW CREATE TABLE t;
SELECT * FROM t;
